version: 2.1
defaults: &defaults
  working_directory: ~/repo
  environment:
    - GOCACHE: "/tmp/go/cache"
    - GOFLAGS: "-mod=readonly"

commands:
  setup_version:
    parameters:
      version:
        type: string
        default: '1.0.0'
    steps:
      - run:
          name: 'setup version'
          command: echo << parameters.version >>

executors:
  default:
    <<: *defaults
    docker:
      - image: circleci/golang:1.14.4

jobs:
  test:
    executor: default
    steps:
      - setup_version
      - run: mkdir -p hoge && echo 'test' > hoge/test
      - persist_to_workspace:
          root: .
          paths:
            - hoge/test

  build_and_deploy:
    executor: default
    steps:
      - setup_version:
          version: '2.0.0'
      - run: mkdir -p fuga && echo 'test' > fuga/test
      - attach_workspace:
          at: .
      - run: ls

workflows:
  version: 2.1
  all:
    jobs:
      - test
      - build_and_deploy:
          requires:
            - test
          filters:
            branches:
              only:
                - master
